### PR TITLE
Set correct os.arch value for ppc64le.

### PR DESCRIPTION
**Pull request by mtbrandy**
Set correct os.arch value for ppc64le.

Backport of https://bugs.openjdk.java.net/browse/JDK-8073139

### CODE REVIEW

**Comment by tellison** [comment]
ok to test

**Comment by karianna** [comment]
OK - This comment should trigger a build.

**Comment by karianna** [comment]
ok to test

**Comment by karianna** [comment]
retest this please

**Comment by karianna** [comment]
"retest this please"

**Comment by tellison** [comment]
retest this please

**Comment by karianna** [comment]
See #1 - Not sure which one of these we'll get tested, but when we do we can kill the other one.

**Pull request closed without merging**
