### PR TITLE
[WIP] Set correct os.arch value for ppc64le.

### PR DESCRIPTION
**Pull request by mtbrandy**
MV: Setting this to WIP as we can always merge it later when we figure out the 'real' workflow

Set correct os.arch value for ppc64le.

Backport of https://bugs.openjdk.java.net/browse/JDK-8073139

### CODE REVIEW

**Comment by karianna** [comment]
@mtbrandy Thanks for submitting this patch - The community hasn't (yet) figured out how we're going to process these so please bear with us whilst we figure out the protocol here

**Comment by tellison** [comment]
Thanks for this patch Matt.  As @karianna wrote, we will use this as our first example to go through the contribution process, so please bear with us as we define the process as we go, overly debate it, mess it up, etc. etc!

It is helpful to have a concrete example to work with as we figure things out.

**Comment by karianna** [comment]
@mtbrandy Apologies - many of us are tied up with the vote on Java 9 and Devoxx UK.  I think what we can do though is get this patch reviewed and merged into a *new* branch which we can call `ppc64le-support` or some such.  Then this can be tested on a PPC (and other) platforms on the build farm and we can at least see the result of that.

**Comment by karianna** [comment]
I'm not sure how we get this PR to merge into a new branch though?

**Comment by mtbrandy** [comment]
Thanks for the update @karianna

**Comment by karianna** [comment]
@mtbrandy Can you modify the PR to merge into a new `os-arch-ppc64le` branch?  I'm not sure that's possible...

**Comment by mtbrandy** [comment]
I don't think there is a way to modify the target branch -- would have to create a new PR.

**Comment by karianna** [comment]
@mtbrandy Would you mind giving that a go?  Sorry for the run around here!

**Comment by mtbrandy** [comment]
I can do that, although I think you first need create the new branch for me to target.

**Comment by karianna** [comment]
OK I've created the `os-arch-ppc64le` branch from the `master` branch.  Now this raises a potential workflow question but as `dev` and `master` haven't diverged too much I think we're OK.

**Comment by mtbrandy** [comment]
Created PR #2.

**Comment by karianna** [comment]
Setting this to WIP as we can always merge it later when we figure out the 'real' workflow

**Comment by mtbrandy** [comment]
Just checking in on this for status.

Also a question: will the CI also have slaves to validate on BE Power Linux and AIX?  I see LE Power Linux is already present.

**Comment by karianna** [comment]
@mtbrandy Apologies this is my fault!  I haven't been able to get the GitHub PR Request builder working for this PR and am at Devoxx UK today/tomorrow and haven't had a chance to dig in further :-(.

Yes we're planning on supporting those two platforms as well.  Luckily IBM is being a great contributor to this effort and they're looking at provisioning and AIX machine!

Thanks again for your patience, appreciate this has not been a quick resolution for you.

**Comment by karianna** [comment]
@mtbrandy I'm back looking at this now - I'm hoping to wrangle this tomorrow and get it building on the farm somehow.

**Comment by gdams** [comment]
successfully built https://ci.adoptopenjdk.net/view/OpenJDK%20PR/job/openjdk_pr_pipeline/6

**Comment by karianna** [comment]
Awesome - OK let's discuss on the Slack channel what do with this PR next (merge it, but into the right branch etc...)

**Comment by karianna** [comment]
@mtbrandy Are you on our Slack group?

**Comment by mtbrandy** [comment]
@karianna Yes, just sent you a message there.

**Comment by gdams** [comment]
landed in https://github.com/AdoptOpenJDK/openjdk-jdk8u/commit/70e2263b4fe3ed9186488d7879d9f43373088221

**Pull request closed without merging**
